global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rafood-api-local"
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000
  - job_name: rafood-database-local
    static_configs:
      - targets: ["database-exporter:9187"]
