global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi-local"
    metrics_path: /metrics
    static_configs:
      - targets:
      # TODO: create a docker container for API
          - localhost:8000
